# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Client
      inputs:
        containerRegistry: 'Docker-Raghav'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: './client'
        tags: 'raghav141988/multi-client'
        repository: 'raghav141988/multi-client'
    - task: Docker@2
      displayName: Build server
      inputs:
        containerRegistry: 'Docker-Raghav'
        command: 'buildAndPush'
        Dockerfile: 'server/Dockerfile'
        buildContext: './server'
        tags: 'raghav141988/multi-server'
        repository: 'raghav141988/multi-server'
    - task: Docker@2
      displayName: Build server
      inputs:
        containerRegistry: 'Docker-Raghav'
        command: 'buildAndPush'
        Dockerfile: 'worker/Dockerfile'
        buildContext: './worker'
        tags: 'raghav141988/multi-worker'
        repository: 'raghav141988/multi-worker'